services:
  
  aimas-api:
    restart: always
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - web

  aimas-frontend:
    restart: always
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web:
    external: true