services:
  
  aimas-api:
    restart: always
    container_name: aimas-api
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - web
    labels:
      - "traefik.enable=true"
      
      # Router para dominio principal
      - "traefik.http.routers.aimas-a.rule=Host(`api.aimas.pro`)"
      - "traefik.http.routers.aimas-a.entrypoints=websecure"
      - "traefik.http.routers.aimas-a.tls.certresolver=myresolver"
      - "traefik.http.routers.aimas-a.service=aimas-api"

      # Routers HTTP que redirigen a HTTPS
      - "traefik.http.routers.aimas-a-http.rule=Host(`api.aimas.pro`)"
      - "traefik.http.routers.aimas-a-http.entrypoints=web"
      - "traefik.http.routers.aimas-a-http.middlewares=https-redirect"

      # Middleware para redirigir a HTTPS
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

      - "traefik.http.services.aimas-api.loadbalancer.server.port=8000"

  aimas-frontend:
    restart: always
    container_name: aimas-frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - web
    labels:
      - "traefik.enable=true"
      
      # Router para dominio principal
      - "traefik.http.routers.aimas-f.rule=Host(`beta.aimas.pro`)"
      - "traefik.http.routers.aimas-f.entrypoints=websecure"
      - "traefik.http.routers.aimas-f.tls.certresolver=myresolver"
      - "traefik.http.routers.aimas-f.service=aimas-frontend"

      # Routers HTTP que redirigen a HTTPS
      - "traefik.http.routers.aimas-f-http.rule=Host(`beta.aimas.pro`)"
      - "traefik.http.routers.aimas-f-http.entrypoints=web"
      - "traefik.http.routers.aimas-f-http.middlewares=https-redirect"

      # Middleware para redirigir a HTTPS
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

      - "traefik.http.services.aimas-frontend.loadbalancer.server.port=3000"

networks:
  web:
    external: true